language: smalltalk
sudo: false

os:
  - linux
 
jobs:
  include:
    - stage: Test
      smalltalk: Pharo-alpha
      smalltalk_config: .smalltalk.ston
    - stage: Test
      smalltalk: Pharo-stable
      smalltalk_config: .smalltalk.ston
    
    - stage: Integration
      smalltalk: Pharo-alpha
      smalltalk_config: .integration.ston
      services:
        - mongodb
    - stage: Integration
      smalltalk: Pharo-stable
      smalltalk_config: .integration.ston
      services:
        - mongodb
